### ISSUE TITLE
Update clicking on Sign up and README

### ISSUE THREAD

**Issue by saleham5** [Necrownyx/Twitch-Account-Toolbox#9]
Great tool but in the final release I don't think getting the coordination of the sign-up bottom and clicking on it works. And the README file is out of date now. Also, check_name() is duplicated.

**Comment by Necrownyx** [comment]
Last time i worked on the project i remember possibly not being able to successfully sign up a new account due to new twitch bot detection systems that have been implemented since the projects creation.

There is a possibility that twitch has moved around the layout of the page which is not uncommon.
You could try commenting out the code that doesn't work and doing those steps manually to see if the program can run successfully.

I know the README is out of date i am getting around to rewriting it soon.

Thank you for highlighting the check_name() function is duplicated i will implement a change soon to remove the unnecessary code.
